# Generated by Django 5.2.3 on 2025-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
