# Generated by Django 5.2.3 on 2025-07-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_document_author_remove_document_status_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
